version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=ewan
      - POSTGRES_DB=debts
      - POSTGRES_PASSWORD=qwerty
      - POSTGRESQL_ENABLE_INITIALIZE=false
      - POSTGRESQL_PORT_NUMBER=5005
    ports:
      - "5005:5005"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: ewanlav/diploma:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/app/configs
  
  migrate:
    image: golang:1.23-alpine
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    command: sh -c "go install github.com/pressly/goose/v3/cmd/goose@latest && goose postgres 'user=ewan password=qwerty dbname=debts host=postgres port=5005 sslmode=disable' up"

volumes:
  pgdata: